FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir psycopg2-binary

COPY db/init/02_load_data.py /app/load_data.py
COPY Pokedex_Limpiado.csv /data/Pokedex_Limpiado.csv
COPY locations /data/locations

CMD ["python", "/app/load_data.py"]
